function saveTxtResults(SparkAll,StackFileName,SparkOutFile,SparkSiteOutFile)
    %% Sparks.
    for k=1:numel(SparkAll)
        SparkAll(k).xyt_len=size(SparkAll(k).Data);
        if numel(SparkAll)==1
            sessionInfo='';
        else
            sessionInfo=['_RecordPhase',num2str(k)];
        end
        writeSingleSparkAll(SparkAll(k),SparkOutFile,StackFileName,sessionInfo,'Spark');
    end
    
    %% Sparks sites.
    for k=1:numel(SparkAll)
        if numel(SparkAll)==1
            sessionInfo='';
        else
            sessionInfo=['_session',num2str(k)];
        end
        writeSingleSparkAll(SparkAll(k),SparkSiteOutFile,StackFileName,sessionInfo,'Site');
    end
    
end
    
function writeSingleSparkAll(S,SparkOutFile,StackFileName,sessionInfo,mode)
    if strcmpi(mode,'spark')
        numelSpark=size(S.SparkProperty,1);
        freq=S.SparkFrequency(1);
        SparkPos=S.SparkPos;
        SparkProperty=S.SparkProperty;
    else
        numelSpark=size(S.SparkSiteProperty,1);
        freq=S.SparkSiteFrequency(1);
        SparkPos=S.SparkSitePos;
        SparkProperty=S.SparkSiteProperty;
    end
    
    msgtitle=['    No.\tVar(cx,cy,ct)\tMass(squm*ms)\tFWHM(um)\tAxisMax(um)\tAxisMin(um)'... 
        '\tAmpFFzero\tTau(ms)\tUpstrokeSigma(ms)\tAmpInt\tBgrInt\tDistToMem(um)\tOrient(degree)\n'];
    msg=['    No.%0.0f\t%s(%0.2f,%0.2f,%0.2f)'...              %No., Center
        '\t%4.2f\t%0.4f\t%0.4f\t%0.4f' ...                     %Spark Mass, FWHM, FWHM_max and FWHM_min.
        '\t%1.4f\t%1.4f\t%1.4f\t%4.2f\t%4.2f\t%1.4f\t%1.4f\n'];%AmpFF0,Tau,Sigma,AmpInt,BgrInt,SparkToMembraneDistance,Orientation
    filelog = fopen(SparkOutFile,'a+');
    fprintf(filelog,'File: %s\n',[StackFileName,sessionInfo]);
    fprintf(filelog,['Detection Settings:',...
        '\nxyt_dim\t%g x %g x %g um, %d x %d x %d pixels',...
        '\nRawGain\t%0.4f',...
        '\nScaleOfDetection(ms)\t[%g:%g:%g]',...
        '\nThresholding\t%g',...
        '\nMinSparkSiteDistance(um)\t%1.3f',...
        '\nAmpLimit(dF/F0)\t[%0.4g,%0.4g]',...
        '\nMassLim(pixels)\t[%g, %g]',...
        '\nFWHMLimit(um)\t[%g, %g]',...
        '\nLeadingTail\t[%g,%g]',...
        '\nTauLimit(ms)\t[%g, %g]',...
        '\nPhaseContrast\t%d',...
        '\nImageTranslation\t%d',...
        '\nCellArea(squm)\t%0.0f',...
        '\nItemNumber\t%d',...
        '\nItemFrequency (/squm/s)\t%0.6f',...
        '\nProgramVersion\t%s\n'],...
        S.xyt_dim(1),S.xyt_dim(2),S.xyt_dim(3),...
        S.xyt_len(1),S.xyt_len(2),S.xyt_len(3),...
        S.Gain(1),...
        S.DetectionScale(1),S.DetectionScale(2),S.DetectionScale(3),...
        S.Threshold,...
        S.MinSparkSiteDistance,...
        0,S.GauAmpLim,...
        S.DetectionLimit(1),S.DetectionLimit(2),...
        S.FWHMLimit(1),S.FWHMLimit(2),...
        S.SparkLim(1),S.SparkLim(2),...
        0,S.TauLim,...
        S.PhaseShiftCorrect,...
        S.ImRegister,...
        sum(S.CellMask(:))*S.xyt_dim(1)*S.xyt_dim(2),...
        numelSpark,...
        freq,...
        S.Creator);
    
    realsparknum=size(SparkProperty,1);
    if realsparknum>0
        fprintf(filelog,msgtitle);
        for j=1:realsparknum
            fprintf(filelog,msg,j,'I',SparkPos(j,7),SparkPos(j,8),SparkPos(j,9),...
                SparkProperty(j,10),SparkProperty(j,1),SparkProperty(j,2),SparkProperty(j,3),...
                SparkProperty(j,6),SparkProperty(j,7),SparkProperty(j,8),SparkProperty(j,4),...
                SparkProperty(j,5),SparkProperty(j,11),SparkProperty(j,12));
        end
    end
    fprintf(filelog,'\n\n');
    fclose(filelog);
end
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
%     
%     for j=1:size(SparkAll(1).CellMask,3)
%         SparkFileLog=fopen(SparkOutFile,'a+');
%         fprintf(SparkFileLog,'File: %s\n',StackFileName);
%         fclose(SparkFileLog);
%         
%         SparkSiteLog = fopen(SparkSiteOutFile,'a+');
%         fprintf(SparkSiteLog,'File: %s\n',StackFileName);
%         fclose(SparkSiteLog);
%         clear('SparkSiteLog','SparkFileLog','ans')
%         
%         % Print out final spark information.
%         if size(SparkAll(1).CellMask,3)==1
%             fprintf('    Saving Spark Information to Hard Disk...');
%             PrintOutResults('I',...
%                 SparkAll(1).xyt_dim,SparkAll(1).IoriginalSize,...
%                 SparkOutFile,...
%                 median([SparkAll(:).Threshold]),...
%                 median([SparkAll(:).Gain]),...
%                 DetectionScale,...
%                 SparkAll(1).MinSparkSiteDistance,...
%                 SparkParameter.GauAmpLim,...
%                 SparkAll(1).TauLim,...
%                 SparkAll(1).DetectionLimit,...
%                 SparkAll(1).FWHMLimit,...
%                 SparkParameter.Leading_Tail,...
%                 SparkParameter.PhaseShiftCorrect,...
%                 SparkParameter.ImRegister,...
%                 SparkAll(1).CellMask,...
%                 SparkAll(1).Creator,...
%                 cat(1,SparkAll(:).SparkPos),...
%                 cat(1,SparkAll(:).SparkProperty),...
%                 median([SparkAll(:).SparkFrequency]),...
%                 false);
%             fprintf('      done\n')
%         else
%             fprintf('    Saving Spark Information ROI%d to Hard Disk...',j);
%             PrintOutResults('I',...
%                 SparkAll(1).xyt_dim,SparkAll(1).IoriginalSize,...
%                 SparkOutFile,...
%                 median([SparkAll(:).Threshold]),...
%                 median([SparkAll(:).Gain]),...
%                 DetectionScale,...
%                 SparkAll(1).MinSparkSiteDistance,...
%                 SparkParameter.GauAmpLim,...
%                 SparkAll(1).TauLim,...
%                 SparkAll(1).DetectionLimit,...
%                 SparkAll(1).FWHMLimit,...
%                 SparkParameter.Leading_Tail,...
%                 SparkParameter.PhaseShiftCorrect,...
%                 SparkParameter.ImRegister,...
%                 SparkAll(k).CellMask(:,:,j),...
%                 SparkAll(1).Creator,...
%                 cat(1,SparkAll(:).(['SparkPos',num2str(j)])),...
%                 cat(1,SparkAll(:).(['SparkProperty',num2str(j)])),...
%                 median([SparkAll(:).SparkFrequency(j)]),...
%                 false);
%             fprintf(' done\n')
%         end
%         
%         % Print out final spark site information.
%         if size(SparkAll(1).CellMask,3)==1
%             fprintf('    Saving Spark SITE Info  to Hard Disk...');
%             PrintOutResults('I',...
%                 SparkAll(1).xyt_dim,SparkAll(1).IoriginalSize,...
%                 SparkSiteOutFile,...
%                 median([SparkAll(:).Threshold]),...
%                 median([SparkAll(:).Gain]),...
%                 DetectionScale,...
%                 SparkAll(1).MinSparkSiteDistance,...
%                 SparkParameter.GauAmpLim,...
%                 SparkAll(1).TauLim,...
%                 SparkAll(1).DetectionLimit,...
%                 SparkAll(1).FWHMLimit,...
%                 SparkParameter.Leading_Tail,...
%                 SparkParameter.PhaseShiftCorrect,...
%                 SparkParameter.ImRegister,...
%                 SparkAll(1).CellMask,...
%                 SparkAll(1).Creator,...
%                 cat(1,SparkAll(:).SparkSitePos),...
%                 cat(1,SparkAll(:).SparkSiteProperty),...
%                 cat(1,SparkAll(:).SparkSiteFrequency),...
%                 false);
%             fprintf('       done\n');
%         else
%             fprintf('    Saving Spark SITE Info   ROI%d to Hard Disk...',j);
%             PrintOutResults('I',...
%                 SparkAll(1).xyt_dim,SparkAll(1).IoriginalSize,...
%                 SparkSiteOutFile,...
%                 median([SparkAll(:).Threshold]),...
%                 median([SparkAll(:).Gain]),...
%                 DetectionScale,...
%                 SparkAll(1).MinSparkSiteDistance,...
%                 SparkParameter.GauAmpLim,...
%                 SparkAll(1).TauLim,...
%                 SparkAll(1).DetectionLimit,...
%                 SparkAll(1).FWHMLimit,...
%                 SparkParameter.Leading_Tail,...
%                 SparkParameter.PhaseShiftCorrect,...
%                 SparkParameter.ImRegister,...
%                 SparkAll(1).CellMask(:,:,j),...
%                 SparkAll(1).Creator,...
%                 cat(1,SparkAll(:).(['SparkSitePos',num2str(j)])),...
%                 cat(1,SparkAll(:).(['SparkSiteProperty',num2str(j)])),...
%                 cat(1,SparkAll(:).SparkSiteFrequency(j)),...
%                 false);
%             fprintf(' done\n');
%         end
%     end
%     
% end
% 
% 
% 
% function PrintOutResults(InputName,xyt_dim,xyt_len,ResultSaving,Threshold,Gain,DetectionScale,...
%         MinSparkSiteDistance,AmpLim,TauLim,AreaLim,FWHMLimit,LeadingTail,PhaseShift,...
%         ImageTranslation,CellMask,Creator,SparkPos,SparkProperty,SparkFrequency)
%     %% Print out all the spark info from the returned results by spark.m.
%     % Syntax:
%     %   1. PrintOutResults(S,'spark');
%     %   2. PrintOutResults(S,'site');
%     
%     
%     %  SparkPos=[x1,x2,y1,y2,z1,z2,xc,yc,z_onset,No.];
%     %  SparkProperty=[FWHM,FWHM_R2,        dAmp,           Bgr,Tau,Sigma,  R2, dAmp_dF/F0,DetctionMass,dF/F0_Mass,No.]; % Old version
%     %  SparkProperty=[FWHM,MajorAxisLength,MinorAxisLength,Amp,Bgr,Amp/Bgr,Tau,Sigma,     DetctionMass,dF/F0_Mass,ToMemDist,Orientation,No.];    
%     %                   1        2              3           4   5     6     7     8          9          10        11        12                   
% 
%     %%
%     if nargin==2 && isstruct(InputName) && ischar(xyt_dim)
%         
%         if isfield(InputName,'ResultSaving')
%             ResultSaving=InputName.ResultSaving;
%         else
%             ResultSaving=[];
%         end
%         Threshold=InputName.Threshold;
%         Gain=InputName.Gain;
%         AreaLim=InputName.DetectionLimit;
%         TauLim=InputName.TauLim;
%         FWHMLimit=InputName.FWHMLimit;
%         MinSparkSiteDistance=InputName.MinSparkSiteDistance;
%         CellMask=InputName.CellMask;
%         Creator=InputName.Creator;
%         if strcmpi(xyt_dim,'site')
%             SparkPos=InputName.SparkSitePos;
%             SparkProperty=InputName.SparkSiteProperty;
%         elseif strcmpi(xyt_dim,'spark')
%             SparkPos=InputName.SparkPos;
%             SparkProperty=InputName.SparkProperty;
%         else
%             disp('    Not defined spark or site information to print.')
%             return;
%         end
%         SparkFrequency=InputName.SparkFrequency;
%         xyt_dim=InputName.xyt_dim;
%         xyt_len=size(InputName.Data);
%         if isfield(InputName,'InputName')
%             InputName=InputName.InputName;
%         else
%             InputName='I';
%         end
%     end
%     
%     %% Display results.
%     msgtitle=['    No.\tVar(cx,cy,ct)\tMass(squm*ms)\tFWHM(um)\tAxisMax(um)\tAxisMin(um)'... 
%         '\tAmpFFzero\tTau(ms)\tUpstrokeSigma(ms)\tAmpInt\tBgrInt\tDistToMem(um)\tOrient(degree)\n'];
%     realsparknum=size(SparkProperty,1);
%     msg=['    No.%0.0f\t%s(%0.2f,%0.2f,%0.2f)'...              %No., Center
%         '\t%4.2f\t%0.4f\t%0.4f\t%0.4f' ...                     %Spark Mass, FWHM, FWHM_max and FWHM_min.
%         '\t%1.4f\t%1.4f\t%1.4f\t%4.2f\t%4.2f\t%1.4f\t%1.4f\n'];%AmpFF0,Tau,Sigma,AmpInt,BgrInt,SparkToMembraneDistance,Orientation
%     
%     %% Print to file.
%     if ~isempty(ResultSaving)
%         logfilename=ResultSaving;
%         filelog = fopen(logfilename,'a+');
%         fprintf(filelog,['Detection Settings:',...
%             '\nxyt_dim\t%g x %g x %g um, %d x %d x %d pixels',...
%             '\nRawGain\t%0.4f',...
%             '\nScaleOfDetection(ms)\t[%g:%g:%g]',...
%             '\nThresholding\t%g',...
%             '\nMinSparkSiteDistance(um)\t%1.3f',...
%             '\nAmpLimit(dF/F0)\t[%0.4g,%0.4g]',...
%             '\nMassLim(pixels)\t[%g, %g]',...
%             '\nFWHMLimit(um)\t[%g, %g]',...
%             '\nLeadingTail\t[%g,%g]',...
%             '\nTauLimit(ms)\t[%g, %g]',...
%             '\nPhaseContrast\t%d',...
%             '\nImageTranslation\t%d',...
%             '\nCellArea(squm)\t%0.0f',...
%             '\nItemNumber\t%d',...
%             '\nItemFrequency (/squm/s)\t%0.6f',...
%             '\nProgramVersion\t%s\n'],...
%             xyt_dim(1),xyt_dim(2),xyt_dim(3),xyt_len(1),xyt_len(2),xyt_len(3),...
%             Gain(1),...
%             DetectionScale(1),DetectionScale(2),DetectionScale(3),...
%             Threshold,...
%             MinSparkSiteDistance,...
%             0,AmpLim,...
%             AreaLim(1),AreaLim(2),...
%             FWHMLimit(1),FWHMLimit(2),...
%             LeadingTail(1),LeadingTail(2),...
%             0,TauLim,...
%             PhaseShift,...
%             ImageTranslation,...
%             sum(CellMask(:))*xyt_dim(1)*xyt_dim(2),...
%             size(SparkProperty,1),...
%             SparkFrequency(1),...
%             Creator);
%         
%         if realsparknum>0
%             fprintf(filelog,msgtitle);
%         end
%         for j=1:realsparknum
%             fprintf(filelog,msg,j,InputName,SparkPos(j,7),SparkPos(j,8),SparkPos(j,9),...
%                 SparkProperty(j,10),SparkProperty(j,1),SparkProperty(j,2),SparkProperty(j,3),...
%                 SparkProperty(j,6),SparkProperty(j,7),SparkProperty(j,8),SparkProperty(j,4),...
%                 SparkProperty(j,5),SparkProperty(j,11),SparkProperty(j,12));
%         end
%         fprintf(filelog,'\n\n');
%         fclose(filelog);
%     end
%     
% end